### ISSUE TITLE
TypeError: svm_train() takes from 1 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by CPZ0721** [mengyuan-lee/learn-to-branch-d2d#3]
Hi, 
Thx your development!
But when I run this code, there is an error at "policy_learn.py", line 123, how to solve it?

I used svmutil by install "libsvm" package... so my command to import svmutils is "from libsvm.svmutil import *"
I don't know whether the error caused by this reason...

**Comment by mengyuan-lee** [comment]
https://github.com/mengyuan-lee/learn-to-branch-d2d/blob/45632e0d008f452e0cee23b00efdbd0237748449/policy_learn.py#L123 Line 123 is about saving the svm model. What's the error message?

**Comment by CPZ0721** [comment]
sorry, It's line 120 abount svm_train()
`m = svm_train(W, y_, x, '-c 0.25 -w1 8')`
The error message is written on the title of issue..

**Comment by mengyuan-lee** [comment]
I got it. I am not quite sure why this issue occurs. Maybe it is incurred by the version of corresponding packages (as you mentioned). You can search it online and rewrite the training command if there is any update about the svm_train().

**Comment by CPZ0721** [comment]
Thank you. How did you install the `svmutil` package? or version?
Because the current version cannot input weight arguments, which is `W` in your program.
https://gitlab.kitware.com/kwiver/libsvm/-/blob/master/python/svmutil.py

**Comment by mengyuan-lee** [comment]
I installed the svmutil package by following the instructions from google. We developed this code in 2017. There may be some update. If svm_train() does not work now, you can search whether there is any alternative way to implement svm where samples can be set to different importance/weights. Hope this suggestion can help.

**Comment by CPZ0721** [comment]
Big Thanks.
I found the weight-SVM download website of the libsvm author, and it really works. For anyone who encounters this problem.
https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/
